flowchart TD
%% generated in 0.01s
    packages__cli2img2nl["packages.cli2img2nl<br/>1 funcs"]
    packages__dsl2img2nl["packages.dsl2img2nl<br/>10 funcs"]
    packages__uri2img2nl["packages.uri2img2nl<br/>7 funcs"]
    src__img2nl["src.img2nl<br/>45 funcs"]
    packages__uri2img2nl -->|3| src__img2nl
    packages__dsl2img2nl -->|2| src__img2nl
    packages__dsl2img2nl -->|2| packages__uri2img2nl
    packages__cli2img2nl -->|1| packages__dsl2img2nl
